import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import AuthProvider from "./auth/AuthProvider";
import "./globals.css";
import "./theme-config.css";
import QueryProvider from "./QueryProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <AuthProvider>
          <QueryProvider>
            <Theme accentColor="teal">
              <NavBar />
              <main className="mt-8">
                <Container>{children}</Container>
              </main>
            </Theme>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
